### ISSUE TITLE
Executing the **create-artifacts.sh** is not creating the folder and files.

### ISSUE THREAD

**Issue by sabarna17** [adhavpavan/BasicNetwork-2.0#8]
Executing the **create-artifacts.sh** is not creating the folder and files.

**Comment by adhavpavan** [comment]
Please add the error which you are getting while running this script.
Make sure that you have proper permission to create a folder there.

**Comment by sabarna17** [comment]
Please find the actual recording of the screen. https://github.com/sabarna17/ERROR_SCREENSHOTS/blob/master/Screen%20Recording%20(09-09-2020%2014-48-21).wmv

**Comment by adhavpavan** [comment]
Please try recreating the network from scratch and let me know if still you are facing an issue.
